#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a55x-common

PRODUCT_COPY_FILES += \
    vendor/samsung/a55x-common/proprietary/product/etc/permissions/privapp-permissions-google-product.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-google-product.xml \
    vendor/samsung/a55x-common/proprietary/product/etc/sysconfig/asi_features.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/asi_features.xml \
    vendor/samsung/a55x-common/proprietary/product/etc/sysconfig/sysconfig_contextual_search.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/sysconfig_contextual_search.xml \
    vendor/samsung/a55x-common/proprietary/product/etc/sysconfig/sysconfig_gemini.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/sysconfig_gemini.xml \
    vendor/samsung/a55x-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/Khronos/OpenCL/samsung.icd:$(TARGET_COPY_OUT_VENDOR)/etc/Khronos/OpenCL/samsung.icd \
    vendor/samsung/a55x-common/proprietary/vendor/etc/dqe/calib_data_colormode0_off.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_off.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.dcm.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.dcm.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.dcm.debug.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.dcm.debug.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.dcm.issuetracker.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.dcm.issuetracker.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.debug.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.debug.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.issuetracker.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.issuetracker.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.kdi.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.kdi.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.kdi.debug.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.kdi.debug.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/gnss/gps.kdi.issuetracker.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.kdi.issuetracker.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init.insmod.vendor_dlkm.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.vendor_dlkm.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/android.hardware.boot-service.exynos.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.boot-service.exynos.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.samsung.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/dmd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dmd.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/hermesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hermesd.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.exynos.wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.exynos.wifi.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.fingerprint.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fingerprint.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.gps.rose.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rose.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.nfc.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.nfc.samsung.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.sensorhub.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sensorhub.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.vendor.onebinary.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.onebinary.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/sec-nfc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/sec-nfc-service.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/secaudiohalaidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secaudiohalaidl.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/teegris.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss-service.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.hardware.security.hermes.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.security.hermes.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.rilchip.slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.slsi.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/init/wifi_slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_slsi.rc \
    vendor/samsung/a55x-common/proprietary/vendor/etc/libnfc-sec-vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-sec-vendor.conf \
    vendor/samsung/a55x-common/proprietary/vendor/etc/libse-gto-hal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libse-gto-hal.conf \
    vendor/samsung/a55x-common/proprietary/vendor/etc/mixer_usb_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_default.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/mixer_usb_gray.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_gray.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/mixer_usb_white.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_white.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/nfc/sec_s3nsen6_hwreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nsen6_hwreg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/nfc/sec_s3nsen6_swreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nsen6_swreg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta_ltn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_ltn.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/plmn_se13_prebuilt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13_prebuilt.bin \
    vendor/samsung/a55x-common/proprietary/vendor/etc/sec_audio_volume_curve.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sec_audio_volume_curve.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/secnvm/k250a_41000001_1.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_41000001_1.img \
    vendor/samsung/a55x-common/proprietary/vendor/etc/secnvm/k250a_41000003_0.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_41000003_0.img \
    vendor/samsung/a55x-common/proprietary/vendor/etc/secnvm/k250a_41000005_c.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_41000005_c.img \
    vendor/samsung/a55x-common/proprietary/vendor/etc/sound_trigger_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_info.xml \
    vendor/samsung/a55x-common/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/a55x-common/proprietary/vendor/etc/wifi/init.insmod.wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/init.insmod.wifi.cfg \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/OD_V3.4.10_11_17_QVGA_ROSE_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.4.10_11_17_QVGA_ROSE_ENN_BGRA.nnc \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/OD_V3.5.3_06_12_VGA_ROSE_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.5.3_06_12_VGA_ROSE_ENN_BGRA.nnc \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_1.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_10.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_10.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_101.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_101.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_102.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_102.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_103.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_103.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_104.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_104.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_105.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_105.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_106.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_106.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_107.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_107.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_108.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_108.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_109.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_109.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_11.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_110.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_110.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_111.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_111.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_112.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_112.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_114.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_114.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_115.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_115.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_116.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_116.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_117.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_117.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_118.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_118.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_119.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_119.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_12.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_12.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_120.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_120.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_121.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_121.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_122.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_122.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_123.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_123.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_124.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_124.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_125.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_125.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_126.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_126.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_127.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_127.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_13.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_13.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_16.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_16.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_17.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_17.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_18.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_18.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_19.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_19.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_2.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_20.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_21.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_22.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_22.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_23.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_24.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_24.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_26.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_27.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_27.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_3.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_32.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_34.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_34.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_36.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_36.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_39.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_39.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_4.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_41.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_41.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_45.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_45.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_46.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_46.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_49.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_49.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_5.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_51.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_51.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_52.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_52.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_53.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_53.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_54.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_54.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_55.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_55.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_56.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_56.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_57.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_57.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_58.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_58.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_59.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_59.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_64.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_64.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_65.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_65.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_66.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_66.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_68.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_68.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_69.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_69.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_7.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_70.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_70.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_71.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_71.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_72.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_72.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_73.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_73.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_74.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_74.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_75.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_75.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_76.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_76.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_77.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_77.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_78.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_78.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_79.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_79.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_8.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_80.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_80.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_81.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_81.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_82.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_82.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_84.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_84.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_85.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_85.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_86.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_86.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_87.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_87.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_88.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_88.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_89.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_89.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_9.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_9.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_90.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_90.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_91.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_91.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_92.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_92.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_93.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_93.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_94.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_94.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_95.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_95.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_96.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_96.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_97.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_97.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_98.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_98.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/RTP_99.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_99.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/SoundAlive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundAlive.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_solution.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_solution_rev00.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution_rev00.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_solution_ti.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution_ti.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_system.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_system.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/compress_capture.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/compress_capture.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xdcm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xdcm.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xkdi.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xkdi.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xnaxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xnaxx.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xnsxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xnsxx.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xskt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xskt.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xzc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xzc.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/gnss/firmware_signed_a55xzh.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xzh.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/icc_profile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/icc_profile.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/is_mcu_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/is_mcu_fw.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/lc3dec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lc3dec.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/lc3enc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lc3enc.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/param_ti.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/param_ti.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/sb_ll.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_ll.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/spkamp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spkamp.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/volctrl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volctrl.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/hydra_config.sdb:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/hydra_config.sdb \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/build_id.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/build_id.txt \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140/wpal:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/wpal \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_bt.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_bt.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_common.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_common.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_wlan.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_wlan_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_sw.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_wlan_t.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_t.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/mx140_wlan_t_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_t_sw.hcf \
    vendor/samsung/a55x-common/proprietary/vendor/firmware/wifi/platform.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/platform.txt

PRODUCT_PACKAGES += \
    android.hardware.boot-V1-ndk.exynos \
    android.weaver@1.0 \
    libEGL_samsung \
    libGLESv1_CM_samsung \
    libGLESv2_samsung \
    gnss_aidl_lib \
    audio.primary.s5e8845 \
    audio.sec_primary.default \
    gatekeeper.s5e8845 \
    libsecaudiohal_aidl \
    sound_trigger.primary.s5e8845 \
    vulkan.samsung \
    libExtIRTA \
    libIRTA \
    libOpenCL \
    libSGPUOpenCL \
    libSamsungPostProcessConvertor \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    lib_SamsungRec_07010 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_SRC384_ver320 \
    lib_SoundAlive_play_plus_ver600 \
    lib_SoundBooster_ver2000 \
    lib_profiler \
    lib_soundaliveresampler \
    libalsautils_sec \
    libarcsoft_dualcam_portraitlighting_preview \
    libaudio-ril \
    libaudioparamupdate \
    libaudioproxy2 \
    libaudioroute_samsung \
    libcsc \
    libdisplaycolor_default \
    libdualcam_refocus_video \
    libegis_fp_normal_sensor_test \
    libeis_core \
    libengmode_client \
    libenn_common_utils \
    libenn_cpu_operators \
    libenn_engine_lib \
    libenn_model \
    libenn_public_api_cpp_lib \
    libenn_user_driver_cpu \
    libenn_user_driver_gpu_lib \
    libenn_user_driver_unified \
    libenn_user_lib \
    libepicoperator \
    libexynos_sensor_interface \
    libexynosscaler \
    libfloatingfeature \
    libgf_in_system_lib \
    libgiantmscl \
    libhdrwrapper \
    libhermes \
    libhermes_bdbridge \
    libhermes_cred \
    libhwjpeg \
    libhwjsqz \
    libhwvault \
    libisosechw \
    liblastaboxmsg \
    libmpbase \
    libprofileparamstorage \
    libqfp_sensortest \
    libril_sem \
    libsamsungcamerahal \
    libsamsungcamerahalutils \
    libsamsungcamerahwl_impl \
    libsec-ril \
    libsec2lsi_conversion \
    libsec_esek \
    libsec_semHalTlc \
    libsec_semRil \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecnativefeature \
    libsecril-client \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsemseg \
    libsensorlistener \
    libsfp_sensor \
    libsfp_teegw \
    libshctrl \
    libskeymint10device \
    libskeymint_cli \
    libspatializerparamstorage \
    libspeakercalibration \
    libspictrl \
    libsynaFpSensorTestNwd \
    libteecl \
    libtinyalsa_samsung \
    libuniapi \
    libuniplugin \
    libuuid_vendor \
    libvkmanager_vendor \
    libvpl \
    libwrappergps \
    nfc_nci_sec \
    sensors.inputvirtual \
    sensors.sensorhub \
    libaudioeffectoffload \
    libmyspace \
    vendor.samsung.hardware.audio-V1-ndk \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V2-ndk \
    vendor.samsung.hardware.bluetooth.audio-impl \
    vendor.samsung.hardware.camera.device-V1-ndk \
    vendor.samsung.hardware.camera.provider-V1-ndk \
    vendor.samsung.hardware.gnss-V3-ndk \
    vendor.samsung.hardware.keymint-V3-ndk \
    vendor.samsung.hardware.nfc_aidl-V1-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.hermes-V1-ndk \
    vendor.samsung.hardware.thermal-V1-ndk \
    vendor.samsung.hardware.thermal@1.0 \
    vendor.samsung.libcolor.custom \
    vendor.samsung_slsi.hardware.epic-V1-ndk \
    vendor.samsung_slsi.hardware.epic@1.0 \
    com.google.android.widevine.nonupdatable \
    HotwordEnrollmentOKGoogleEx4CORTEXM4 \
    HotwordEnrollmentXGoogleEx4CORTEXM4 \
    com.android.hotwordenrollment.common.util \
    android.hardware.boot-service.exynos.xml \
    iweaver_aidl_v2_manifest.xml \
    sec-nfc-service.xml \
    secaudiohalaidl_manifest.xml \
    vendor.samsung.hardware.camera.provider-service.xml \
    vendor.samsung.hardware.radio.exclude.slsi.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.security.hermes.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    dmd \
    hermesd \
    android.hardware.boot-service.exynos \
    android.hardware.gatekeeper-service \
    android.hardware.security.keymint-service.samsung \
    gps \
    gpsd_K44 \
    rild \
    sec.android.hardware.nfc-service \
    secaudiohalaidl \
    vendor.samsung.hardware.camera.provider-service_64 \
    vendor.samsung.hardware.gnss-service \
    vendor.samsung.hardware.security.hermes-service \
    init.insmod \
    tzdaemon \
    tzts_daemon

PRODUCT_PACKAGES += \
    vendor_Khronos_OpenCL_vendors_samsung_icd
